
rule /^(GPL\d+)\/?(codes|info\.yaml)?/ do |t|
  t.name =~ /^(GPL\d+)\/?(codes|info\.yaml)?/
  platform = $1
  file = $2
  GEO::SOFT.GPL(platform, file.nil? ? t.name : File.dirname(t.name))
end

rule /^(GDS\d+)\/?(values|info\.yaml)?/ do |t|
  t.name =~ /^(GDS\d+)\/?(values|info\.yaml)?/
  dataset = $1
  file = $2
  GEO::SOFT.GDS(dataset, file.nil? ? t.name : File.dirname(t.name))
end
