# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rbbt-GE"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Miguel Vazquez"]
  s.date = "2012-01-31"
  s.description = "Gene Expression in RBBT"
  s.email = "miguel.vazquez@cnio.es"
  s.extra_rdoc_files = [
    "LICENSE"
  ]
  s.files = [
    "LICENSE",
    "lib/rbbt/GE.rb",
    "lib/rbbt/GE/GEO.rb",
    "share/install/GEO/Rakefile",
    "share/lib/R/MA.R"
  ]
  s.homepage = "http://github.com/mikisvaz/rbbt-GE"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Gene Expression in RBBT"
  s.test_files = ["test/test_helper.rb", "test/rbbt/GE/test_GEO.rb"]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rbbt-util>, [">= 0"])
    else
      s.add_dependency(%q<rbbt-util>, [">= 0"])
    end
  else
    s.add_dependency(%q<rbbt-util>, [">= 0"])
  end
end

